name: Generate Space Shooter Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Space Shooter
        uses: czl9707/gh-space-shooter@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: VivekChaurasiya95
          output-path: output/space-shooter.gif
          strategy: random
          fps: 40
          commit-message: "Update space-shooter contribution graph"
