name: Generate Space Shooter Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Space Shooter
        run: |
          python -m pip install --upgrade pip
          pip install gh-space-shooter
          mkdir -p output
          gh-space-shooter VivekChaurasiya95 --output output/space-shooter.gif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output/space-shooter.gif
          git commit -m "Update space-shooter contribution graph" || echo "No changes to commit"
          git push
